= Spring Cloud
:basedir: ../../..
:toc: left

Spring Cloud provides tools for developers to quickly build some of
the common patterns in distributed systems (e.g. configuration
management, service discovery, circuit breakers, intelligent routing,
micro-proxy, control bus, one-time tokens, global locks, leadership
election, distributed sessions, cluster state). Coordination of
distributed systems leads to boiler plate patterns, and using Spring
Cloud developers can quickly stand up services and applications that
implement those patterns. They will work well in any distributed
environment, including the developer's own laptop, bare metal data
centres, and managed platforms such as Cloud Foundry.

== Features

Spring Cloud focuses on providing good out of box experience for typical use cases 
and extensibility mechanism to cover others. 

* Distributed/versioned configuration
* Service registration and discovery
* Routing
* Service-to-service calls
* Load balancing
* Circuit Breakers
* Global locks
* Leadership election and cluster state
* Distributed messaging

include::{basedir}/commons/docs/src/main/asciidoc/spring-cloud-commons.adoc[]

include::{basedir}/config/docs/src/main/asciidoc/spring-cloud-config.adoc[]

include::{basedir}/netflix/docs/src/main/asciidoc/spring-cloud-netflix.adoc[]

include::{basedir}/bus/docs/src/main/asciidoc/spring-cloud-bus.adoc[]

include::{basedir}/cli/docs/src/main/asciidoc/spring-cloud-cli.adoc[]

include::{basedir}/security/docs/src/main/asciidoc/spring-cloud-security.adoc[]

include::{basedir}/cluster/docs/src/main/asciidoc/spring-cloud-cluster.adoc[]

